export interface MultipleDownload {
  label: string
  url: string
}

export interface Movie {
  id: string
  title: string
  poster: string
  backdrop?: string
  genre: string[]
  year: number
  rating: number
  views: number
  quality: string
  slug: string
  duration?: string
  description: string
  cast?: string[]
  director?: string
  country: string
  language: string
  downloadUrl?: string
  videoUrl?: string
  multipleDownloads?: MultipleDownload[]
  isFeatured?: boolean
  isNew?: boolean
  isTrending?: boolean
}

export const movies: Movie[] = [
  {
    id: "1",
    title: "Skincare (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/09/Skincare-2024-Download-NetNaija.xyz_.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/09/Skincare-2024-Download-NetNaija.xyz_.webp",
    genre: ["Drama", "Thriller"],
    year: 2024,
    rating: 7.2,
    views: 125000,
    quality: "HD",
    slug: "skincare-2024",
    duration: "1h 38m",
    description:
      "Famed aesthetician Hope's skincare business faces sabotage when longtime rival Angel opens a boutique across the street. Aided by her friend Jordan, Hope seeks to uncover who's trying to ruin her reputation.",
    cast: ["Elizabeth Banks", "Lewis Pullman", "Luis Gerardo Méndez"],
    director: "Austin Peters",
    country: "United States",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/9729b9572899b0fe/Skincare_(2024)_(NetNaija.xyz).mkv",
    isFeatured: true,
    isNew: true,
    isTrending: true,
  },
  {
    id: "2",
    title: "Dìdi (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/09/Didi-2024-Download-NetNaija.xyz_.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/09/Didi-2024-Download-NetNaija.xyz_.webp",
    genre: ["Comedy", "Drama"],
    year: 2024,
    rating: 8.1,
    views: 89000,
    quality: "HD",
    slug: "didi-2024",
    duration: "1h 33m",
    description:
      "In 2008, during the last month of summer before high school begins, an impressionable 13-year-old Taiwanese American boy learns what his family can't teach him: how to skate, how to flirt, and how to love your mom.",
    cast: ["Izaac Wang", "Joan Chen", "Shirley Chen"],
    director: "Sean Wang",
    country: "United States",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/d523df2f71926118/D%C3%ACdi_(2024)_(NetNaija.xyz).mkv",
    isNew: true,
  },
  {
    id: "3",
    title: "Lady Scorpions (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/09/Lady-Scorpions-2024-Download-NetNaija.xyz_.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/09/Lady-Scorpions-2024-Download-NetNaija.xyz_.webp",
    genre: ["Action"],
    year: 2024,
    rating: 6.8,
    views: 156000,
    quality: "HD",
    slug: "lady-scorpions-2024",
    duration: "1h 21m",
    description:
      "An ex-FBI agent's fight against a crime syndicate becomes personal when they kidnap her granddaughter. She and her daughter, both martial arts masters, form an unstoppable team.",
    cast: ["Cynthia Rothrock", "Caitlin Dechelle", "Jeff Fahey"],
    country: "United States",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/b4ba3ec4cd6566e0/Lady_Scorpions_(2024)_(NetNaija.xyz).mkv",
    isTrending: true,
  },
  {
    id: "4",
    title: "While You Were Sleeping (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/09/While-You-Were-Sleeping-2024-Download-NetNaija.xyz_.webp",
    backdrop:
      "https://netnaija.xyz/wp-content/uploads/2024/09/While-You-Were-Sleeping-2024-Download-NetNaija.xyz_.webp",
    genre: ["Drama", "Mystery"],
    year: 2024,
    rating: 7.5,
    views: 67000,
    quality: "HD",
    slug: "while-you-were-sleeping-2024",
    duration: "1h 40m",
    description:
      "A woman who has selective amnesia loses her husband to a car accident. Overwhelmed with sorrow, she traces his journey and faces the unexpected truth.",
    cast: ["Choo Ja-hyun", "Lee Moo-saeng", "Son Sook"],
    country: "South Korea",
    language: "Korean",
    downloadUrl: "https://netnaijafiles.xyz/1c7d9610ecc99340/While_You_Were_Sleeping_(2024)_(NetNaija.xyz).mkv",
  },
  {
    id: "5",
    title: "The Good Half (2023)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/09/The-Good-Half-2023-Download-NetNaija.xyz_.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/09/The-Good-Half-2023-Download-NetNaija.xyz_.webp",
    genre: ["Comedy", "Drama"],
    year: 2023,
    rating: 7.0,
    views: 45000,
    quality: "HD",
    slug: "the-good-half-2023",
    duration: "1h 36m",
    description:
      "An emotionally distant writer returns to his hometown for his beloved mother's funeral, after having spent years successfully avoiding interactions with his family.",
    cast: ["Nick Jonas", "Brittany Snow", "Matt Walsh"],
    country: "United States",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/532898988bebc2dc/The_Good_Half_(2023)_(NetNaija.xyz).mkv",
  },
  {
    id: "6",
    title: "Trap (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/08/Trap-2024-Download-NetNaija.xyz_.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/08/Trap-2024-Download-NetNaija.xyz_.webp",
    genre: ["Crime", "Horror", "Mystery", "Thriller"],
    year: 2024,
    rating: 8.3,
    views: 234000,
    quality: "4K",
    slug: "trap-2024",
    duration: "1h 45m",
    description:
      "A father and teen daughter attend a pop concert, where they realize they're at the center of a dark and sinister event.",
    cast: ["Josh Hartnett", "Ariel Donoghue", "Saleka"],
    director: "M. Night Shyamalan",
    country: "United States",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/0e91dec87ca03aef/Trap_(2024)_(NetNaija.xyz).mkv",
    isFeatured: true,
    isTrending: true,
  },
  {
    id: "7",
    title: "Borderlands (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/08/Borderlands-2024-Download-NetNaija.xyz_.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/08/Borderlands-2024-Download-NetNaija.xyz_.webp",
    genre: ["Action", "Adventure", "Comedy", "Sci-Fi"],
    year: 2024,
    rating: 6.9,
    views: 189000,
    quality: "4K",
    slug: "borderlands-2024",
    duration: "1h 41m",
    description:
      "Returning to her home planet, an infamous bounty hunter forms an unexpected alliance with a team of unlikely heroes.",
    cast: ["Cate Blanchett", "Kevin Hart", "Jack Black"],
    country: "United States",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/246e0d453cb2f29b/Borderlands_(2024)_(NetNaija.xyz).mkv",
    isTrending: true,
  },
  {
    id: "8",
    title: "Inside Out 2 (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/08/Inside-Out-2-2024-Download-NetNaija.xyz_.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/08/Inside-Out-2-2024-Download-NetNaija.xyz_.webp",
    genre: ["Animation", "Family", "Adventure", "Comedy"],
    year: 2024,
    rating: 9.1,
    views: 456000,
    quality: "4K",
    slug: "inside-out-2-2024",
    duration: "1h 36m",
    description:
      "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions!",
    cast: ["Amy Poehler", "Maya Hawke", "Kensington Tallman"],
    country: "United States",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/21a58a24f55d5b92/Inside_Out_2_(2024)_(NetNaija.xyz).mkv",
    isFeatured: true,
    isTrending: true,
  },
  {
    id: "9",
    title: "First Shift (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/08/First-Shift-2024-Download-NetNaija.xyz_.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/08/First-Shift-2024-Download-NetNaija.xyz_.webp",
    genre: ["Action", "Crime", "Drama", "Thriller"],
    year: 2024,
    rating: 6.5,
    views: 78000,
    quality: "HD",
    slug: "first-shift-2024",
    duration: "1h 29m",
    description:
      "NYPD veteran Mike and rookie Angela tackle a high-stakes day on New York's toughest streets, diving headfirst into a vortex of danger and action.",
    cast: ["Gino Anthony Pesi", "Kristen Renton", "James McMenamin"],
    country: "United States",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/6a6ab0e23be34978/First_Shift_(2024)_(NetNaija.xyz).mkv",
  },
  {
    id: "10",
    title: "Out Come the Wolves (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/08/Out-Come-the-Wolves-2024-Download-NetNaija.xyz_.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/08/Out-Come-the-Wolves-2024-Download-NetNaija.xyz_.webp",
    genre: ["Action", "Horror", "Thriller"],
    year: 2024,
    rating: 7.1,
    views: 92000,
    quality: "HD",
    slug: "out-come-the-wolves-2024",
    duration: "1h 27m",
    description:
      "At a cabin deep in the wilderness, a weekend of hunting turns to mayhem and a fight for survival when a pack of wolves attack.",
    cast: ["Damon Runyan", "Joris Jarsky", "Missy Peregrym"],
    country: "Canada",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/d9a1db4587d0c91d/Out_Come_the_Wolves_(2024)_(NetNaija.xyz).mkv",
  },
  {
    id: "11",
    title: "Freedom Hair (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/08/Trap-2024-Download-NetNaija.xyz_.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/08/Trap-2024-Download-NetNaija.xyz_.webp",
    genre: ["Drama", "History"],
    year: 2024,
    rating: 7.8,
    views: 54000,
    quality: "HD",
    slug: "freedom-hair-2024",
    duration: "1h 42m",
    description:
      "When a mother decides to start a natural hair braiding business to achieve financial independence, she must overcome obstacles imposed by a powerful cosmetology cartel.",
    cast: ["Sophia Bush", "Erica Tazel", "Catherine Dyer"],
    country: "United States",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/ef1bb9ef0fa7f68c/Freedom_Hair_(2024)_(NetNaija.xyz).mkv",
  },
  {
    id: "12",
    title: "The Deliverance (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/08/The-Deliverance-2024-Download-NetNaija.xyz_.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/08/The-Deliverance-2024-Download-NetNaija.xyz_.webp",
    genre: ["Horror", "Thriller"],
    year: 2024,
    rating: 6.9,
    views: 167000,
    quality: "HD",
    slug: "the-deliverance-2024",
    duration: "1h 52m",
    description:
      "Single parent Ebony Jackson moves her family to a new home for a fresh start, but something evil already lives there.",
    cast: ["Andra Day", "Glenn Close", "Aunjanue Ellis-Taylor"],
    country: "United States",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/6a5c8600f0c9a9ea/The_Deliverance_(2024)_(NetNaija.xyz).mkv",
    isTrending: true,
  },
  {
    id: "13",
    title: "A Legend (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/08/A-Legend-2024-Download-NetNaija.xyz_.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/08/A-Legend-2024-Download-NetNaija.xyz_.webp",
    genre: ["Action", "Adventure", "Drama", "Fantasy"],
    year: 2024,
    rating: 7.3,
    views: 134000,
    quality: "HD",
    slug: "a-legend-2024",
    duration: "2h 9m",
    description:
      "An archeologist noticed that the texture of the relics discovered during the excavation of a glacier closely resembled a jade pendant seen in one of his dreams.",
    cast: ["Jackie Chan", "Zhang Yixing", "Guli Nazha"],
    country: "China",
    language: "Chinese",
    downloadUrl: "https://netnaijafiles.xyz/891b61cc660965c0/A_Legend_(2024)_(NetNaija.xyz).mp4",
  },
  {
    id: "14",
    title: "Buddy (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/08/Buddy-2024-Download-NetNaija.xyz_.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/08/Buddy-2024-Download-NetNaija.xyz_.webp",
    genre: ["Action", "Adventure", "Comedy", "Sci-Fi"],
    year: 2024,
    rating: 6.4,
    views: 87000,
    quality: "HD",
    slug: "buddy-2024",
    duration: "2h 3m",
    description:
      "A teddy bear named Buddy is in trouble and asks pilot Aditya Ram for help. Can the duo join forces and help each other out?",
    cast: ["Allu Sirish", "Ajmal Ameer", "Sriram Reddy Polasane"],
    country: "India",
    language: "Telugu",
    downloadUrl: "https://netnaijafiles.xyz/54ba7af8a2d9234d/Buddy_(2024)_(NetNaija.xyz).mkv",
  },
  {
    id: "15",
    title: "Bad Newz (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/08/Bad-Newz-2024-Download-NetNaija.xyz_.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/08/Bad-Newz-2024-Download-NetNaija.xyz_.webp",
    genre: ["Comedy", "Drama", "Romance"],
    year: 2024,
    rating: 6.8,
    views: 112000,
    quality: "HD",
    slug: "bad-newz-2024",
    duration: "2h 22m",
    description:
      "After a whirlwind marriage with social media influencer Akhil Chadha that ends in divorce, chef Saloni Bagga meets hotelier Gurbir Pannu.",
    cast: ["Vicky Kaushal", "Triptii Dimri", "Ammy Virk"],
    country: "India",
    language: "Hindi",
    downloadUrl: "https://netnaijafiles.xyz/021f4c6e18a49231/Bad_Newz_(2024)_(NetNaija.xyz).mkv",
  },
  {
    id: "16",
    title: "Buzz House: The Movie (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/08/Buzz-House_-The-Movie-2024-Download-NetNaija.xyz_.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/08/Buzz-House_-The-Movie-2024-Download-NetNaija.xyz_.webp",
    genre: ["Comedy", "Horror"],
    year: 2024,
    rating: 5.9,
    views: 43000,
    quality: "HD",
    slug: "buzz-house-the-movie-2024",
    duration: "1h 47m",
    description:
      "The next season of Buzz House is the most ambitious yet. Selly has prepared many surprises for the participants.",
    cast: ["Costi Max", "Andrei Șelaru", "Erika Isac"],
    country: "Romania",
    language: "Romanian",
    downloadUrl: "https://netnaijafiles.xyz/338f16e04a980fba/Buzz_House_The_Movie_(2024)_(NetNaija.xyz).mkv",
  },
  {
    id: "17",
    title: "Escape (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/08/Escape-2024-Download-NetNaija.xyz_.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/08/Escape-2024-Download-NetNaija.xyz_.webp",
    genre: ["Action", "Drama", "Thriller"],
    year: 2024,
    rating: 8.2,
    views: 198000,
    quality: "HD",
    slug: "escape-2024",
    duration: "1h 34m",
    description:
      "After completing his required decade of military service and being honored as a hero, a North Korean sergeant makes a sudden shocking attempt to defect to the South.",
    cast: ["Lee Je-hoon", "Koo Kyo-hwan", "Hong Xa-bin"],
    country: "South Korea",
    language: "Korean",
    downloadUrl: "https://netnaijafiles.xyz/7289f1494d403738/Escape_(2024)_(NetNaija.xyz).mkv",
    isTrending: true,
  },
  {
    id: "18",
    title: "Harold and the Purple Crayon (2024)",
    poster:
      "https://netnaija.xyz/wp-content/uploads/2024/08/Harold-and-the-Purple-Crayon-2024-Download-NetNaija.xyz_.webp",
    backdrop:
      "https://netnaija.xyz/wp-content/uploads/2024/08/Harold-and-the-Purple-Crayon-2024-Download-NetNaija.xyz_.webp",
    genre: ["Adventure", "Animation", "Comedy", "Fantasy", "Kids"],
    year: 2024,
    rating: 6.1,
    views: 89000,
    quality: "HD",
    slug: "harold-and-the-purple-crayon-2024",
    duration: "1h 30m",
    description:
      "Inside of his book, adventurous Harold can make anything come to life simply by drawing it. After he grows up and draws himself off the book's pages and into the physical world.",
    cast: ["Zachary Levi", "Zooey Deschanel", "Lil Rel Howery"],
    country: "United States",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/46273e4b1b280fc9/Harold_and_the_Purple_Crayon_(2024)_(NetNaija.xyz).mkv",
  },
  {
    id: "19",
    title: "Ride (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/08/Ride-2024-Download-NetNaija.xyz_.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/08/Ride-2024-Download-NetNaija.xyz_.webp",
    genre: ["Crime", "Drama"],
    year: 2024,
    rating: 6.7,
    views: 76000,
    quality: "HD",
    slug: "ride-2024",
    duration: "1h 36m",
    description:
      "Desperate to raise money for his daughter's cancer treatment, a retired bull rider teams up with his estranged son and resorts to robbery.",
    cast: ["C. Thomas Howell", "Jake Allyn", "Annabeth Gish"],
    country: "United States",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/ca1387a98264019a/Ride_(2024)_(NetNaija.xyz).mkv",
  },
  {
    id: "20",
    title: "Someone Like You (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/08/Someone-Like-You-2024-Download-NetNaija.xyz_.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/08/Someone-Like-You-2024-Download-NetNaija.xyz_.webp",
    genre: ["Drama", "Romance"],
    year: 2024,
    rating: 7.4,
    views: 65000,
    quality: "HD",
    slug: "someone-like-you-2024",
    duration: "1h 58m",
    description:
      "Shocking news hits after young architect Dawson loses his best friend London. In his heartbreak, Dawson is compelled to launch an impossible search for London's secret sister.",
    cast: ["Sarah Fisher", "Jake Allyn", "Lynn Collins"],
    country: "United States",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/f779eaebd39a5a60/Someone_Like_You_(2024)_(NetNaija.xyz).mkv",
  },
  {
    id: "21",
    title: "Adam Sandler: Love You (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/08/Adam-Sandler_-Love-You-2024-Download-NetNaija.xyz_.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/08/Adam-Sandler_-Love-You-2024-Download-NetNaija.xyz_.webp",
    genre: ["Comedy"],
    year: 2024,
    rating: 7.6,
    views: 234000,
    quality: "HD",
    slug: "adam-sandler-love-you-2024",
    duration: "1h 4m",
    description:
      "Adam Sandler hits the stage for a thrillingly unpredictable comedy special featuring songs, jokes, party-crashing dogs and plenty of love.",
    cast: ["Adam Sandler", "Dan Bulla"],
    country: "United States",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/e8aaab26518bdf8e/Adam_Sandler_Love_You_(2024)_(NetNaija.xyz).mkv",
  },
  {
    id: "22",
    title: "The Lockdown (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/08/The-Lockdown-2024-Download-NetNaija.xyz_.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/08/The-Lockdown-2024-Download-NetNaija.xyz_.webp",
    genre: ["Action"],
    year: 2024,
    rating: 6.3,
    views: 98000,
    quality: "HD",
    slug: "the-lockdown-2024",
    duration: "1h 58m",
    description:
      "Siblings Charlie and Jack are trapped in Myanmar's toughest prison and accused of a crime they didn't commit. Forced into televised fights against other inmates.",
    cast: ["Caity Lotz", "Leo Howard", "Hon Ping Tang"],
    country: "United States",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/c7c8aed7876d3b84/The_Lockdown_(2024)_(NetNaija.xyz).mkv",
  },
  {
    id: "23",
    title: "Running on Empty (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/08/Running-on-Empty-2024-Download-NetNaija.xyz_.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/08/Running-on-Empty-2024-Download-NetNaija.xyz_.webp",
    genre: ["Comedy", "Romance"],
    year: 2024,
    rating: 6.8,
    views: 72000,
    quality: "HD",
    slug: "running-on-empty-2024",
    duration: "1h 29m",
    description:
      "When Mort finds out he has less than a year to live, his fiancé Nicole leaves him and he's forced to accept his fate.",
    cast: ["Keir Gilchrist", "Lucy Hale", "Jay Pharoah"],
    country: "United States",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/83ffb52e3b08a902/Running_on_Empty_(2024)_(NetNaija.xyz).mkv",
  },
  {
    id: "24",
    title: "Wallbanger (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/08/Wallbanger-2024-Download-NetNaija.xyz_.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/08/Wallbanger-2024-Download-NetNaija.xyz_.webp",
    genre: ["Comedy", "Romance"],
    year: 2024,
    rating: 6.2,
    views: 58000,
    quality: "HD",
    slug: "wallbanger-2024",
    duration: "1h 47m",
    description:
      "Caroline is a young, single interior designer living in San Francisco who has been without a boyfriend for some time. She moves into an apartment that seems perfect.",
    cast: ["Amadeus Serafini", "Kelli Berglund", "Ryan McPartlin"],
    country: "United States",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/cff4423426605ba5/Wallbanger_(2024)_(NetNaija.xyz).mkv",
  },
  {
    id: "25",
    title: "Kinds of Kindness (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/08/Kinds-of-Kindness-2024-Download-NetNaija.xyz_.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/08/Kinds-of-Kindness-2024-Download-NetNaija.xyz_.webp",
    genre: ["Drama", "Comedy"],
    year: 2024,
    rating: 7.9,
    views: 145000,
    quality: "HD",
    slug: "kinds-of-kindness-2024",
    duration: "2h 44m",
    description:
      "A triptych fable following a man without choice who tries to take control of his own life; a policeman who is alarmed that his wife who was missing-at-sea has returned.",
    cast: ["Emma Stone", "Jesse Plemons", "Willem Dafoe"],
    country: "Ireland",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/0efb4fef3368f6c4/Kinds_of_Kindness_(2024)_(NetNaija.xyz).mkv",
    isTrending: true,
  },
  {
    id: "26",
    title: "The Greatest Ever (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/08/The-Greatest-Ever-2024-Download-NetNaija.xyz_.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/08/The-Greatest-Ever-2024-Download-NetNaija.xyz_.webp",
    genre: ["Drama", "Family"],
    year: 2024,
    rating: 6.9,
    views: 34000,
    quality: "HD",
    slug: "the-greatest-ever-2024",
    duration: "1h 32m",
    description:
      "Riley Waters, a young girl with the heart of a champion, strives to leave her mark on the world despite having all odds stacked against her.",
    cast: ["Alexandra Bradley", "Cate Elefante", "Bradley Stryker"],
    country: "United States",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/b1f7102762c04550/The_Greatest_Ever_(2024)_(NetNaija.xyz).mkv",
  },
  {
    id: "27",
    title: "The Supremes at Earl's All-You-Can-Eat (2024)",
    poster:
      "https://netnaija.xyz/wp-content/uploads/2024/08/The-Supremes-at-Earls-All-You-Can-Eat-2024-Download-NetNaija.xyz_.webp",
    backdrop:
      "https://netnaija.xyz/wp-content/uploads/2024/08/The-Supremes-at-Earls-All-You-Can-Eat-2024-Download-NetNaija.xyz_.webp",
    genre: ["Comedy", "Drama"],
    year: 2024,
    rating: 7.5,
    views: 89000,
    quality: "HD",
    slug: "the-supremes-at-earls-all-you-can-eat-2024",
    duration: "2h 4m",
    description:
      "Three lifelong best friends known as 'The Supremes' share the unbreakable bonds of sisterhood from decades of weathering life's storms.",
    cast: ["Aunjanue Ellis-Taylor", "Sanaa Lathan", "Uzo Aduba"],
    country: "United States",
    language: "English",
    downloadUrl:
      "https://netnaijafiles.xyz/17795809e5714e7f/The_Supremes_at_Earls_All-You-Can-Eat_(2024)_(NetNaija.xyz).mkv",
  },
  {
    id: "28",
    title: "Munjya (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/08/Munjya-2024-Download-NetNaija.xyz_.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/08/Munjya-2024-Download-NetNaija.xyz_.webp",
    genre: ["Comedy", "Horror"],
    year: 2024,
    rating: 7.1,
    views: 156000,
    quality: "HD",
    slug: "munjya-2024",
    duration: "2h 3m",
    description:
      "A young man's visit to his native village unveils a family secret and a vengeful spirit, Munjya, who wants to get married.",
    cast: ["Sharvari Wagh", "Abhay Verma", "Ayush Ulagadde"],
    country: "India",
    language: "Hindi",
    downloadUrl: "https://netnaijafiles.xyz/97c64f32a60bd991/Munjya_(2024)_(NetNaija.xyz).mkv",
  },
  {
    id: "29",
    title: "Tòkunbọ̀ (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/08/Tokunbo%CC%80-2024-Download-NetNaija.xyz_-1.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/08/Tokunbo%CC%80-2024-Download-NetNaija.xyz_-1.webp",
    genre: ["Crime", "Drama", "Thriller"],
    year: 2024,
    rating: 7.8,
    views: 123000,
    quality: "HD",
    slug: "tokunbo-2024",
    duration: "1h 54m",
    description:
      "An ex-car smuggler is given three hours to deliver a government official's daughter to her captor – or else his family will suffer the consequences.",
    cast: ["Gideon Okeke", "Funlola Aofiyebi-Raimi", "Darasimi Nadi"],
    country: "Nigeria",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/741acbe829427537/Tokunbo_(2024)_(NetNaija.xyz).mkv",
    isTrending: true,
  },
  {
    id: "30",
    title: "The Killer (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/08/The-Killer-2024-Download-NetNaija.xyz_.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/08/The-Killer-2024-Download-NetNaija.xyz_.webp",
    genre: ["Action", "Crime", "Thriller"],
    year: 2024,
    rating: 7.6,
    views: 187000,
    quality: "HD",
    slug: "the-killer-2024",
    duration: "2h 6m",
    description:
      "Zee is a feared contract killer known as 'the Queen of the Dead,' but when she refuses to murder a young blind woman, she finds herself hunted.",
    cast: ["Nathalie Emmanuel", "Omar Sy", "Sam Worthington"],
    country: "United States",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/34cae48ac31704b5/The_Killer_(2024)_(NetNaija.xyz).mkv",
    isTrending: true,
  },
  {
    id: "31",
    title: "Incoming (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/08/Incoming-2024-Download-NetNaija.xyz_.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/08/Incoming-2024-Download-NetNaija.xyz_.webp",
    genre: ["Comedy"],
    year: 2024,
    rating: 6.4,
    views: 98000,
    quality: "HD",
    slug: "incoming-2024",
    duration: "1h 31m",
    description: "Four incoming freshmen navigate the terrors of adolescence at their first-ever high school party.",
    cast: ["Mason Thames", "Isabella Ferreira", "Ali Gallo"],
    country: "United States",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/32647cc111f6b401/Incoming_(2024)_(NetNaija.xyz).mkv",
  },
  {
    id: "32",
    title: "Hell Hole (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/08/Hell-Hole-2024-Download-NetNaija.xyz_.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/08/Hell-Hole-2024-Download-NetNaija.xyz_.webp",
    genre: ["Horror"],
    year: 2024,
    rating: 6.1,
    views: 76000,
    quality: "HD",
    slug: "hell-hole-2024",
    duration: "1h 33m",
    description:
      "Far away, in the desolate Serbian wilderness, a U.S.-led fracking crew uncover a dormant monster gestating inside a centuries-old French soldier.",
    cast: ["Toby Poser", "John Adams", "Max Portman"],
    country: "United States",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/69afc6a3b4dc819c/Hell_Hole_(2024)_(NetNaija.xyz).mkv",
  },
  {
    id: "33",
    title: "Raayan (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/08/Raayan-2024-Download-NetNaija.xyz_.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/08/Raayan-2024-Download-NetNaija.xyz_.webp",
    genre: ["Action", "Drama", "Thriller"],
    year: 2024,
    rating: 8.4,
    views: 234000,
    quality: "HD",
    slug: "raayan-2024",
    duration: "2h 25m",
    description:
      "Raayan, a simpleton patriarch has to protect his family when they inadvertently get muddled in a violent world with whirlpool of murder, debauchery, feud, politics and power.",
    cast: ["Dhanush", "Dushara Vijayan", "Sundeep Kishan"],
    country: "India",
    language: "Tamil",
    downloadUrl: "https://netnaijafiles.xyz/20c40b5ac33470f8/Raayan_(2024)_(NetNaija.xyz).mkv",
    isFeatured: true,
    isTrending: true,
  },
  {
    id: "34",
    title: "Greedy People (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/08/Greedy-People-2024-Download-NetNaija.xyz_.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/08/Greedy-People-2024-Download-NetNaija.xyz_.webp",
    genre: ["Comedy", "Crime", "Mystery"],
    year: 2024,
    rating: 7.2,
    views: 145000,
    quality: "HD",
    slug: "greedy-people-2024",
    duration: "1h 52m",
    description:
      "The eclectic residents of a small, picturesque island town must navigate a sensational murder and the discovery of a million dollars.",
    cast: ["Himesh Patel", "Lily James", "Joseph Gordon-Levitt"],
    country: "United States",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/278a3774d7752871/Greedy_People_(2024)_(NetNaija.xyz).mkv",
  },
  {
    id: "35",
    title: "Longlegs (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/08/Longlegs-2024-Download-NetNaija.xyz_.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/08/Longlegs-2024-Download-NetNaija.xyz_.webp",
    genre: ["Crime", "Horror", "Thriller"],
    year: 2024,
    rating: 8.7,
    views: 298000,
    quality: "HD",
    slug: "longlegs-2024",
    duration: "1h 41m",
    description:
      "In pursuit of a serial killer, an FBI agent uncovers a series of occult clues that she must solve to end his terrifying killing spree.",
    cast: ["Maika Monroe", "Nicolas Cage", "Blair Underwood"],
    country: "United States",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/c0443ae209ee19e7/Longlegs_(2024)_(NetNaija.xyz).mkv",
    isFeatured: true,
    isTrending: true,
  },
  {
    id: "36",
    title: "Kalki 2898 AD (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/08/Kalki-2898-AD-2024-Download-NetNaija.xyz_.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/08/Kalki-2898-AD-2024-Download-NetNaija.xyz_.webp",
    genre: ["Drama", "Action", "Fantasy", "Sci-Fi"],
    year: 2024,
    rating: 8.9,
    views: 456000,
    quality: "4K",
    slug: "kalki-2898-ad-2024",
    duration: "3h 1m",
    description:
      "Bhairava, tired of the oppressive confines of his homeland and the perilous life of a bounty hunter, yearns for a more comfortable existence in the Complex.",
    cast: ["Amitabh Bachchan", "Prabhas", "Deepika Padukone"],
    country: "India",
    language: "Telugu",
    downloadUrl: "https://netnaijafiles.xyz/159f3e0823e78f29/Kalki_2898_AD_(2024)_(NetNaija.xyz).mkv",
    isFeatured: true,
    isTrending: true,
  },
  {
    id: "37",
    title: "The Wolf of Wall Street (2013)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/07/The-Wolf-of-Wall-Street-2013-download-netnaija.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/07/The-Wolf-of-Wall-Street-2013-download-netnaija.webp",
    genre: ["Crime", "Drama", "Comedy"],
    year: 2013,
    rating: 8.2,
    views: 1234000,
    quality: "HD",
    slug: "the-wolf-of-wall-street-2013",
    duration: "3h 0m",
    description:
      "A New York stockbroker refuses to cooperate in a large securities fraud case involving corruption on Wall Street, corporate banking world and mob infiltration.",
    cast: ["Leonardo DiCaprio", "Jonah Hill", "Margot Robbie"],
    country: "United States",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/e086a8ee5d38f833/The_Wolf_of_Wall_Street_(2013)_(NetNaija.xyz).mkv",
    isFeatured: true,
  },
  {
    id: "38",
    title: "American Gangster (2007)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/07/American-Gangster-2007-download-netnaija.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/07/American-Gangster-2007-download-netnaija.webp",
    genre: ["Crime", "Drama"],
    year: 2007,
    rating: 7.8,
    views: 987000,
    quality: "HD",
    slug: "american-gangster-2007",
    duration: "2h 37m",
    description:
      "Following the death of his employer and mentor, Bumpy Johnson, Frank Lucas establishes himself as the number one importer of heroin in the Harlem district of Manhattan.",
    cast: ["Russell Crowe", "Denzel Washington", "Chiwetel Ejiofor"],
    country: "United States",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/6026e3686379b02d/American_Gangster_(2007)_(NetNaija.xyz).mkv",
  },
  {
    id: "39",
    title: "Joker (2019)",
    poster: "https://netnaija.xyz/wp-content/uploads/2020/06/882HHK.jpg",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2020/06/882HHK.jpg",
    genre: ["Crime", "Drama", "Thriller"],
    year: 2019,
    rating: 8.4,
    views: 2345000,
    quality: "4K",
    slug: "joker-2019",
    duration: "2h 2m",
    description:
      "Forever alone in a crowd, failed comedian Arthur Fleck seeks connection as he walks the streets of Gotham City. Arthur wears two masks — the one he paints for his day job as a clown, and the guise he projects in a futile attempt to feel like he's part of the world around him.",
    cast: ["Joaquin Phoenix", "Robert De Niro", "Zazie Beetz"],
    country: "United States",
    language: "English",
    downloadUrl: "https://www.downloadbetter.com/YwpcEElGt63/joker-2019-netnaija-com-mp4.html",
    isFeatured: true,
    isTrending: true,
  },
  {
    id: "40",
    title: "The Irishman (2019)",
    poster: "https://netnaija.xyz/wp-content/uploads/2020/06/xl7HHK.jpg",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2020/06/xl7HHK.jpg",
    genre: ["Crime", "Drama"],
    year: 2019,
    rating: 7.8,
    views: 1876000,
    quality: "4K",
    slug: "the-irishman-2019",
    duration: "3h 29m",
    description:
      "Frank 'The Irishman' Sheeran is a man with a lot on his mind. The former labor union high official and hitman, learned to kill serving in Italy during the Second World War.",
    cast: ["Robert De Niro", "Al Pacino", "Joe Pesci"],
    director: "Martin Scorsese",
    country: "United States",
    language: "English",
    downloadUrl: "https://www.downloadbetter.com/hrnTlIlCy56/the-irishman-2019-netnaija-com-mp4.html",
    isFeatured: true,
  },
  {
    id: "41",
    title: "John Wick: Chapter 3 – Parabellum (2019)",
    poster: "https://netnaija.xyz/wp-content/uploads/2020/06/JgcHHK.jpg",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2020/06/JgcHHK.jpg",
    genre: ["Action", "Crime", "Thriller"],
    year: 2019,
    rating: 7.4,
    views: 1567000,
    quality: "4K",
    slug: "john-wick-chapter-3-parabellum-2019",
    duration: "2h 11m",
    description:
      "Super-assassin John Wick is on the run after killing a member of the international assassin's guild, and with a $14 million price tag on his head – he is the target of hit men and women everywhere.",
    cast: ["Keanu Reeves", "Halle Berry", "Ian McShane"],
    country: "United States",
    language: "English",
    downloadUrl: "https://www.downloadbetter.com/VeEmbQTcn42/john-wick-chapter-3-parabellum-2019-netnaija-com-mp4.html",
    isTrending: true,
  },
  {
    id: "42",
    title: "Spider-Man: Far from Home (2019)",
    poster: "https://netnaija.xyz/wp-content/uploads/2020/06/qX1HHK.jpg",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2020/06/qX1HHK.jpg",
    genre: ["Action", "Adventure", "Sci-Fi"],
    year: 2019,
    rating: 7.4,
    views: 2134000,
    quality: "4K",
    slug: "spider-man-far-from-home-2019",
    duration: "2h 9m",
    description:
      "Peter Parker's relaxing European vacation takes an unexpected turn when Nick Fury shows up in his hotel room to recruit him for a mission.",
    cast: ["Tom Holland", "Samuel L. Jackson", "Jake Gyllenhaal"],
    country: "United States",
    language: "English",
    downloadUrl: "https://www.downloadbetter.com/fviyiyMfa61/spider-man-far-from-home-2019-netnaija-com-mp4.html",
    isTrending: true,
  },
  {
    id: "43",
    title: "Avengers: Endgame (2019)",
    poster: "/placeholder.svg?height=450&width=300",
    backdrop: "/placeholder.svg?height=450&width=300",
    genre: ["Action", "Adventure", "Drama"],
    year: 2019,
    rating: 8.4,
    views: 5678000,
    quality: "4K",
    slug: "avengers-endgame-2019",
    duration: "3h 1m",
    description:
      "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
    cast: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo"],
    country: "United States",
    language: "English",
    isFeatured: true,
    isTrending: true,
  },
  {
    id: "44",
    title: "Coco (2017)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/07/Coco-2017-download-netnaija.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/07/Coco-2017-download-netnaija.webp",
    genre: ["Animation", "Adventure", "Drama", "Family", "Musical"],
    year: 2017,
    rating: 8.4,
    views: 1876000,
    quality: "4K",
    slug: "coco-2017",
    duration: "1h 45m",
    description:
      "Despite his family's baffling generations-old ban on music, Miguel dreams of becoming an accomplished musician like his idol, Ernesto de la Cruz.",
    cast: ["Anthony Gonzalez", "Gael García Bernal", "Benjamin Bratt"],
    country: "United States",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/437d3adff0e0c587/Coco_(2017)_(NetNaija.xyz).mkv",
  },
  {
    id: "45",
    title: "The Garfield Movie (2024)",
    poster: "https://netnaija.xyz/wp-content/uploads/2024/07/The-Garfield-Movie-2024-download-netnaija.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2024/07/The-Garfield-Movie-2024-download-netnaija.webp",
    genre: ["Adventure", "Animation", "Comedy", "Family"],
    year: 2024,
    rating: 6.1,
    views: 234000,
    quality: "HD",
    slug: "the-garfield-movie-2024",
    duration: "1h 41m",
    description:
      "Garfield, the world-famous, Monday-hating, lasagna-loving indoor cat, is about to have a wild outdoor adventure!",
    cast: ["Chris Pratt", "Samuel L. Jackson", "Hannah Waddingham"],
    country: "United States",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/8e2b185b469f5a93/The_Garfield_Movie_(2024)_(NetNaija.xyz).mkv",
    isNew: true,
  },
  {
    id: "46",
    title: "Fast & Furious Presents: Hobbs & Shaw (2019)",
    poster: "https://netnaija.xyz/wp-content/uploads/2020/06/7V1HHK.jpg",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2020/06/7V1HHK.jpg",
    genre: ["Action", "Adventure"],
    year: 2019,
    rating: 6.5,
    views: 1234000,
    quality: "4K",
    slug: "fast-furious-presents-hobbs-shaw-2019",
    duration: "2h 17m",
    description:
      "Lawman Luke Hobbs and outcast Deckard Shaw form an unlikely alliance when a cyber-genetically enhanced villain threatens the future of humanity.",
    cast: ["Dwayne Johnson", "Jason Statham", "Idris Elba"],
    country: "United States",
    language: "English",
    downloadUrl:
      "https://www.downloadbetter.com/DYxndmVjw07/fast-furious-presents-hobbs-shaw-2019-netnaija-com-mp4.html",
  },
  {
    id: "47",
    title: "Toy Story 4 (2019)",
    poster: "https://netnaija.xyz/wp-content/uploads/2020/06/771HHK.jpg",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2020/06/771HHK.jpg",
    genre: ["Animation", "Adventure", "Comedy", "Family"],
    year: 2019,
    rating: 7.7,
    views: 1876000,
    quality: "4K",
    slug: "toy-story-4-2019",
    duration: "1h 40m",
    description:
      "Woody, Buzz Lightyear and the rest of the gang embark on a road trip with Bonnie and a new toy named Forky.",
    cast: ["Tom Hanks", "Tim Allen", "Annie Potts"],
    country: "United States",
    language: "English",
    downloadUrl: "https://www.downloadbetter.com/mwPXPpqOE25/toy-story-4-2019-netnaija-com-mp4.html",
  },
  {
    id: "48",
    title: "The Lion King (2019)",
    poster: "https://netnaija.xyz/wp-content/uploads/2020/06/J9qHHK.jpg",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2020/06/J9qHHK.jpg",
    genre: ["Animation", "Adventure", "Drama", "Family"],
    year: 2019,
    rating: 6.8,
    views: 2345000,
    quality: "4K",
    slug: "the-lion-king-2019",
    duration: "1h 58m",
    description:
      "After the murder of his father, a young lion prince flees his kingdom only to learn the true meaning of responsibility and bravery.",
    cast: ["Donald Glover", "Beyoncé", "James Earl Jones"],
    country: "United States",
    language: "English",
    downloadUrl: "https://www.downloadbetter.com/AqcSlFtGP01/the-lion-king-2019-netnaija-com-mp4.html",
  },
  {
    id: "49",
    title: "Sinners (2025)",
    poster: "https://9jarocks.net/wp-content/uploads/2025/05/Sinners_Poster.jpg",
    backdrop: "https://9jarocks.net/wp-content/uploads/2025/05/Sinners_Poster.jpg",
    genre: ["Thriller", "Horror", "Drama"],
    year: 2025,
    rating: 7.2,
    views: 45000,
    quality: "HD",
    slug: "sinners-2025",
    duration: "1h 47m",
    description:
      "Trying to leave their troubled lives behind, twin brothers return to their hometown to start again, only to discover that an even greater evil is waiting to welcome them back.",
    country: "United States",
    language: "English",
    downloadUrl: "https://loadedfiles.org/6b2b50ea61eab6fc",
    isNew: true,
    isTrending: true,
  },
  {
    id: "50",
    title: "Fountain of Youth (2025)",
    poster:
      "https://9jarocks.net/wp-content/uploads/2025/05/MV5BNWRlZmU3ZTItM2JlYi00YTg1LTgxNTItMjMyNzIyZWY5YWJmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    backdrop:
      "https://9jarocks.net/wp-content/uploads/2025/05/MV5BNWRlZmU3ZTItM2JlYi00YTg1LTgxNTItMjMyNzIyZWY5YWJmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    genre: ["Adventure", "Fantasy", "Action"],
    year: 2025,
    rating: 6.8,
    views: 32000,
    quality: "HD",
    slug: "fountain-of-youth-2025",
    duration: "2h 3m",
    description:
      "Two estranged siblings join forces to seek the legendary Fountain of Youth. Using historical clues, they embark on an epic quest filled with adventure. If successful, the mythical fountain could grant them immortality.",
    country: "United States",
    language: "English",
    downloadUrl: "https://loadedfiles.org/735610e25bc81d95",
    isNew: true,
  },
  {
    id: "51",
    title: "Murderbot (2025) Season 1",
    poster: "https://9jarocks.net/wp-content/uploads/2025/05/Murderbot_Poster.jpg",
    backdrop: "https://9jarocks.net/wp-content/uploads/2025/05/Murderbot_Poster.jpg",
    genre: ["Sci-Fi", "Action", "Drama"],
    year: 2025,
    rating: 8.1,
    views: 78000,
    quality: "HD",
    slug: "murderbot-2025-season-1",
    duration: "Episode 3 Added",
    description:
      "A security android struggles with emotions and free will while balancing dangerous missions and desire for isolation, evading detection of its self-hacking as it finds its place.",
    country: "United States",
    language: "English",
    downloadUrl: "https://loadedfiles.org/6c349edf3aed4a21",
    isNew: true,
    isTrending: true,
  },
  {
    id: "52",
    title: "Beyoncé Bowl (2024)",
    poster: "https://9jarocks.net/wp-content/uploads/2025/05/Beyonc-Bowl_Poster.jpg",
    backdrop: "https://9jarocks.net/wp-content/uploads/2025/05/Beyonc-Bowl_Poster.jpg",
    genre: ["Music", "Documentary"],
    year: 2024,
    rating: 8.5,
    views: 156000,
    quality: "4K",
    slug: "beyonce-bowl-2024",
    duration: "1h 15m",
    description: "Beyoncé's halftime performance during Netflix's first-ever NFL Christmas Gameday.",
    cast: ["Beyoncé"],
    country: "United States",
    language: "English",
    downloadUrl: "https://loadedfiles.org/77b482226dc11e54",
    isTrending: true,
  },
  {
    id: "53",
    title: "What Happens After the Massacre? (2025)",
    poster: "https://9jarocks.net/wp-content/uploads/2025/05/What-Happens-After-the-Massacre_Poster.jpg",
    backdrop: "https://9jarocks.net/wp-content/uploads/2025/05/What-Happens-After-the-Massacre_Poster.jpg",
    genre: ["Horror", "Thriller"],
    year: 2025,
    rating: 6.9,
    views: 23000,
    quality: "HD",
    slug: "what-happens-after-the-massacre-2025",
    duration: "1h 32m",
    description:
      "Dawn has illuminated Camp Kiwassee, and after a night of brutal killings from the infamous Red Face, Mike and Henry are tasked with putting the pieces of the camp back together.",
    country: "United States",
    language: "English",
    downloadUrl: "https://loadedfiles.org/f5699d582f486442",
    isNew: true,
  },
  {
    id: "54",
    title: "WWII Declassified: The New World Rescues the Old (2025)",
    poster:
      "https://9jarocks.net/wp-content/uploads/2025/05/WWII-Declassified-The-New-World-Rescues-the-Old_Poster.jpg",
    backdrop:
      "https://9jarocks.net/wp-content/uploads/2025/05/WWII-Declassified-The-New-World-Rescues-the-Old_Poster.jpg",
    genre: ["Documentary", "History", "War"],
    year: 2025,
    rating: 8.2,
    views: 67000,
    quality: "HD",
    slug: "wwii-declassified-the-new-world-rescues-the-old-2025",
    duration: "1h 58m",
    description:
      "From the retreat at Dunkirk to the invasion of Normandy, this documentary follows WWII's turning points. Witness the Allies' struggle, strategic battles, and ultimate push toward victory as they fight to reclaim Europe from Nazi control.",
    country: "United States",
    language: "English",
    downloadUrl: "https://loadedfiles.org/f1553df2892d6d3c",
    isNew: true,
  },
  {
    id: "55",
    title: "S.T.A.L.K.E.R.: Shadow of the Zone (2024)",
    poster: "https://9jarocks.net/wp-content/uploads/2025/05/S-T-A-L-K-E-R-Shadow-of-the-Zone_Poster.jpg",
    backdrop: "https://9jarocks.net/wp-content/uploads/2025/05/S-T-A-L-K-E-R-Shadow-of-the-Zone_Poster.jpg",
    genre: ["Sci-Fi", "Action", "Thriller"],
    year: 2024,
    rating: 7.4,
    views: 89000,
    quality: "HD",
    slug: "stalker-shadow-of-the-zone-2024",
    duration: "1h 43m",
    description:
      "A seasoned Free Stalker tasked with guiding a band of Mercenaries deep into The Zone to investigate a paranormal radio signal. Based on the S.T.A.L.K.E.R. video-game series by G.S.C. Game World.",
    country: "Ukraine",
    language: "English",
    downloadUrl: "https://loadedfiles.org/ff7c30cbb3aaaef2",
    isTrending: true,
  },
  {
    id: "56",
    title: "HIT: The Third Case (2025)",
    poster:
      "https://netnaija.xyz/wp-content/uploads/2025/05/HIT_-The-Third-Case-2025-Download-NetNaija.xyz_-683x1024.webp",
    backdrop:
      "https://netnaija.xyz/wp-content/uploads/2025/05/HIT_-The-Third-Case-2025-Download-NetNaija.xyz_-683x1024.webp",
    genre: ["Action", "Crime", "Thriller"],
    year: 2025,
    rating: 7.6,
    views: 54000,
    quality: "HD",
    slug: "hit-the-third-case-2025",
    duration: "2h 12m",
    description:
      "The Homicide Intervention Team (HIT) sends ruthless police officer Arjun Sarkaar to find a group of killers and stop their grisly murder spree.",
    country: "India",
    language: "Telugu",
    downloadUrl: "https://netnaijafiles.xyz/fc1032c9f0562798/HIT__The_Third_Case_(2025)_(NetNaija.xyz).srt",
    isNew: true,
  },
  {
    id: "57",
    title: "Retro (2025)",
    poster: "https://netnaija.xyz/wp-content/uploads/2025/05/Retro-2025-Download-NetNaija.xyz_-683x1024.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2025/05/Retro-2025-Download-NetNaija.xyz_-683x1024.webp",
    genre: ["Action", "Drama", "Crime"],
    year: 2025,
    rating: 7.1,
    views: 41000,
    quality: "HD",
    slug: "retro-2025",
    duration: "2h 5m",
    description:
      "Raised by a criminal father, Paarivel Kannan leaves behind his adoptive family to build a quiet life with his love, Rukmini. But his violent past won't let him go.",
    country: "India",
    language: "Tamil",
    downloadUrl: "https://netnaijafiles.xyz/8493c50ec426e55c/Retro_(2025)_(NetNaija.xyz).mkv",
    isNew: true,
  },
  {
    id: "58",
    title: "Thudarum (2025)",
    poster: "https://netnaija.xyz/wp-content/uploads/2025/05/Thudarum-2025-Download-NetNaija.xyz_-683x1024.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2025/05/Thudarum-2025-Download-NetNaija.xyz_-683x1024.webp",
    genre: ["Thriller", "Crime", "Drama"],
    year: 2025,
    rating: 6.8,
    views: 28000,
    quality: "HD",
    slug: "thudarum-2025",
    duration: "1h 54m",
    description:
      "A taxi driver finds himself embroiled in a dangerous conspiracy after his car is confiscated by a corrupt police officer.",
    country: "India",
    language: "Tamil",
    downloadUrl: "https://netnaijafiles.xyz/8c2da4fbc7c8880e/Thudarum_(2025)_(NetNaija.xyz).mkv",
    isNew: true,
  },
  {
    id: "59",
    title: "Implosion: The Titanic Sub Disaster (2025)",
    poster:
      "https://9jarocks.net/wp-content/uploads/2025/05/MV5BZmM2ZGY1NzQtZGEyMi00Mjc2LWE5MGItN2Y0MjU1MDg2Y2ExXkEyXkFqcGc@._V1_Ratio1.0036_AL_.jpg",
    backdrop:
      "https://9jarocks.net/wp-content/uploads/2025/05/MV5BZmM2ZGY1NzQtZGEyMi00Mjc2LWE5MGItN2Y0MjU1MDg2Y2ExXkEyXkFqcGc@._V1_Ratio1.0036_AL_.jpg",
    genre: ["Documentary", "Drama"],
    year: 2025,
    rating: 7.8,
    views: 123000,
    quality: "HD",
    slug: "implosion-the-titanic-sub-disaster-2025",
    duration: "1h 45m",
    description:
      "In June 2023, the OceanGate submersible imploded, killing all on board. Uncover the extraordinary story of what led to the disaster and its potential prevention, with exclusive access to the USCG investigation and never-before-seen video.",
    country: "United States",
    language: "English",
    downloadUrl: "https://loadedfiles.org/444fb1b298dd6913",
    isNew: true,
    isTrending: true,
  },
  {
    id: "60",
    title: "Walking with the Tall Whites: Aftermath (2024)",
    poster: "https://9jarocks.net/wp-content/uploads/2025/05/Walking-with-the-Tall-Whites-Aftermath_Poster.jpg",
    backdrop: "https://9jarocks.net/wp-content/uploads/2025/05/Walking-with-the-Tall-Whites-Aftermath_Poster.jpg",
    genre: ["Documentary", "Sci-Fi"],
    year: 2024,
    rating: 6.9,
    views: 34000,
    quality: "HD",
    slug: "walking-with-the-tall-whites-aftermath-2024",
    duration: "1h 38m",
    description:
      "Walking with the Tall Whites Aftermath is the second documentary in the series, following Charles Hall as he explores humanity's hidden coexistence with three extraterrestrial species on Earth. Based on 'Millennial Hospitality,' Book series.",
    country: "United States",
    language: "English",
    downloadUrl: "https://loadedfiles.org/1c4ff1eeb12d163c",
  },
  {
    id: "61",
    title: "Grimsburg Season 2",
    poster: "https://9jarocks.net/wp-content/uploads/2025/02/Grimsburg_Poster.jpg",
    backdrop: "https://9jarocks.net/wp-content/uploads/2025/02/Grimsburg_Poster.jpg",
    genre: ["Animation", "Comedy", "Crime"],
    year: 2025,
    rating: 7.3,
    views: 87000,
    quality: "HD",
    slug: "grimsburg-season-2",
    duration: "Episodes 1-3 Added",
    description:
      "Marvin Flute, who might be the greatest detective ever, has one mystery he still can't crack: his family. He will follow every lead he's got to redeem himself with the ex-wife he never stopped loving.",
    country: "United States",
    language: "English",
    downloadUrl: "https://loadedfiles.org/cd2329272216e5eb",
    isNew: true,
  },
  {
    id: "62",
    title: "Sinners (2025)",
    poster: "https://9jarocks.net/wp-content/uploads/2025/05/Sinners_Poster.jpg",
    backdrop: "https://9jarocks.net/wp-content/uploads/2025/05/Sinners_Poster.jpg",
    genre: ["Thriller", "Horror", "Drama"],
    year: 2025,
    rating: 7.2,
    views: 45000,
    quality: "HD",
    slug: "sinners-2025-new",
    duration: "1h 47m",
    description:
      "Trying to leave their troubled lives behind, twin brothers return to their hometown to start again, only to discover that an even greater evil is waiting to welcome them back.",
    country: "United States",
    language: "English",
    downloadUrl: "https://loadedfiles.org/6b2b50ea61eab6fc",
    isNew: true,
    isTrending: true,
  },
  {
    id: "63",
    title: "Fountain of Youth (2025)",
    poster:
      "https://9jarocks.net/wp-content/uploads/2025/05/MV5BNWRlZmU3ZTItM2JlYi00YTg1LTgxNTItMjMyNzIyZWY5YWJmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    backdrop:
      "https://9jarocks.net/wp-content/uploads/2025/05/MV5BNWRlZmU3ZTItM2JlYi00YTg1LTgxNTItMjMyNzIyZWY5YWJmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    genre: ["Adventure", "Fantasy", "Action"],
    year: 2025,
    rating: 6.8,
    views: 32000,
    quality: "HD",
    slug: "fountain-of-youth-2025-new",
    duration: "2h 3m",
    description:
      "Two estranged siblings join forces to seek the legendary Fountain of Youth. Using historical clues, they embark on an epic quest filled with adventure. If successful, the mythical fountain could grant them immortality.",
    country: "United States",
    language: "English",
    downloadUrl: "https://loadedfiles.org/735610e25bc81d95",
    isNew: true,
  },
  {
    id: "64",
    title: "Murderbot (2025) Season 1",
    poster: "https://9jarocks.net/wp-content/uploads/2025/05/Murderbot_Poster.jpg",
    backdrop: "https://9jarocks.net/wp-content/uploads/2025/05/Murderbot_Poster.jpg",
    genre: ["Sci-Fi", "Action", "Drama"],
    year: 2025,
    rating: 8.1,
    views: 78000,
    quality: "HD",
    slug: "murderbot-2025-season-1-new",
    duration: "Episode 3 Added",
    description:
      "A security android struggles with emotions and free will while balancing dangerous missions and desire for isolation, evading detection of its self-hacking as it finds its place.",
    country: "United States",
    language: "English",
    downloadUrl: "https://loadedfiles.org/6c349edf3aed4a21",
    isNew: true,
    isTrending: true,
  },
  {
    id: "65",
    title: "Beyoncé Bowl (2024)",
    poster: "https://9jarocks.net/wp-content/uploads/2025/05/Beyonc-Bowl_Poster.jpg",
    backdrop: "https://9jarocks.net/wp-content/uploads/2025/05/Beyonc-Bowl_Poster.jpg",
    genre: ["Music", "Documentary"],
    year: 2024,
    rating: 8.5,
    views: 156000,
    quality: "4K",
    slug: "beyonce-bowl-2024-new",
    duration: "1h 15m",
    description: "Beyoncé's halftime performance during Netflix's first-ever NFL Christmas Gameday.",
    cast: ["Beyoncé"],
    country: "United States",
    language: "English",
    downloadUrl: "https://loadedfiles.org/77b482226dc11e54",
    isTrending: true,
  },
  {
    id: "66",
    title: "What Happens After the Massacre? (2025)",
    poster: "https://9jarocks.net/wp-content/uploads/2025/05/What-Happens-After-the-Massacre_Poster.jpg",
    backdrop: "https://9jarocks.net/wp-content/uploads/2025/05/What-Happens-After-the-Massacre_Poster.jpg",
    genre: ["Horror", "Thriller"],
    year: 2025,
    rating: 6.9,
    views: 23000,
    quality: "HD",
    slug: "what-happens-after-the-massacre-2025-new",
    duration: "1h 32m",
    description:
      "Dawn has illuminated Camp Kiwassee, and after a night of brutal killings from the infamous Red Face, Mike and Henry are tasked with putting the pieces of the camp back together.",
    country: "United States",
    language: "English",
    downloadUrl: "https://loadedfiles.org/f5699d582f486442",
    isNew: true,
  },
  {
    id: "67",
    title: "WWII Declassified: The New World Rescues the Old (2025)",
    poster:
      "https://9jarocks.net/wp-content/uploads/2025/05/WWII-Declassified-The-New-World-Rescues-the-Old_Poster.jpg",
    backdrop:
      "https://9jarocks.net/wp-content/uploads/2025/05/WWII-Declassified-The-New-World-Rescues-the-Old_Poster.jpg",
    genre: ["Documentary", "History", "War"],
    year: 2025,
    rating: 8.2,
    views: 67000,
    quality: "HD",
    slug: "wwii-declassified-the-new-world-rescues-the-old-2025-new",
    duration: "1h 58m",
    description:
      "From the retreat at Dunkirk to the invasion of Normandy, this documentary follows WWII's turning points. Witness the Allies' struggle, strategic battles, and ultimate push toward victory as they fight to reclaim Europe from Nazi control.",
    country: "United States",
    language: "English",
    downloadUrl: "https://loadedfiles.org/f1553df2892d6d3c",
    isNew: true,
  },
  {
    id: "68",
    title: "S.T.A.L.K.E.R.: Shadow of the Zone (2024)",
    poster: "https://9jarocks.net/wp-content/uploads/2025/05/S-T-A-L-K-E-R-Shadow-of-the-Zone_Poster.jpg",
    backdrop: "https://9jarocks.net/wp-content/uploads/2025/05/S-T-A-L-K-E-R-Shadow-of-the-Zone_Poster.jpg",
    genre: ["Sci-Fi", "Action", "Thriller"],
    year: 2024,
    rating: 7.4,
    views: 89000,
    quality: "HD",
    slug: "stalker-shadow-of-the-zone-2024-new",
    duration: "1h 43m",
    description:
      "A seasoned Free Stalker tasked with guiding a band of Mercenaries deep into The Zone to investigate a paranormal radio signal. Based on the S.T.A.L.K.E.R. video-game series by G.S.C. Game World.",
    country: "Ukraine",
    language: "English",
    downloadUrl: "https://loadedfiles.org/ff7c30cbb3aaaef2",
    isTrending: true,
  },
  {
    id: "69",
    title: "HIT: The Third Case (2025)",
    poster:
      "https://netnaija.xyz/wp-content/uploads/2025/05/HIT_-The-Third-Case-2025-Download-NetNaija.xyz_-683x1024.webp",
    backdrop:
      "https://netnaija.xyz/wp-content/uploads/2025/05/HIT_-The-Third-Case-2025-Download-NetNaija.xyz_-683x1024.webp",
    genre: ["Action", "Crime", "Thriller"],
    year: 2025,
    rating: 7.6,
    views: 54000,
    quality: "HD",
    slug: "hit-the-third-case-2025-new",
    duration: "2h 12m",
    description:
      "The Homicide Intervention Team (HIT) sends ruthless police officer Arjun Sarkaar to find a group of killers and stop their grisly murder spree.",
    country: "India",
    language: "Telugu",
    downloadUrl: "https://netnaijafiles.xyz/fc1032c9f0562798/HIT__The_Third_Case_(2025)_(NetNaija.xyz).mkv",
    isNew: true,
  },
  {
    id: "70",
    title: "Retro (2025)",
    poster: "https://netnaija.xyz/wp-content/uploads/2025/05/Retro-2025-Download-NetNaija.xyz_-683x1024.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2025/05/Retro-2025-Download-NetNaija.xyz_-683x1024.webp",
    genre: ["Action", "Drama", "Crime"],
    year: 2025,
    rating: 7.1,
    views: 41000,
    quality: "HD",
    slug: "retro-2025-new",
    duration: "2h 5m",
    description:
      "Raised by a criminal father, Paarivel Kannan leaves behind his adoptive family to build a quiet life with his love, Rukmini. But his violent past won't let him go.",
    country: "India",
    language: "Tamil",
    downloadUrl: "https://netnaijafiles.xyz/8493c50ec426e55c/Retro_(2025)_(NetNaija.xyz).mkv",
    isNew: true,
  },
  {
    id: "71",
    title: "Thudarum (2025)",
    poster: "https://netnaija.xyz/wp-content/uploads/2025/05/Thudarum-2025-Download-NetNaija.xyz_-683x1024.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2025/05/Thudarum-2025-Download-NetNaija.xyz_-683x1024.webp",
    genre: ["Thriller", "Crime", "Drama"],
    year: 2025,
    rating: 6.8,
    views: 28000,
    quality: "HD",
    slug: "thudarum-2025-new",
    duration: "1h 54m",
    description:
      "A taxi driver finds himself embroiled in a dangerous conspiracy after his car is confiscated by a corrupt police officer.",
    country: "India",
    language: "Tamil",
    downloadUrl: "https://netnaijafiles.xyz/8c2da4fbc7c8880e/Thudarum_(2025)_(NetNaija.xyz).mkv",
    isNew: true,
  },
  {
    id: "72",
    title: "Implosion: The Titanic Sub Disaster (2025)",
    poster:
      "https://9jarocks.net/wp-content/uploads/2025/05/MV5BZmM2ZGY1NzQtZGEyMi00Mjc2LWE5MGItN2Y0MjU1MDg2Y2ExXkEyXkFqcGc@._V1_Ratio1.0036_AL_.jpg",
    backdrop:
      "https://9jarocks.net/wp-content/uploads/2025/05/MV5BZmM2ZGY1NzQtZGEyMi00Mjc2LWE5MGItN2Y0MjU1MDg2Y2ExXkEyXkFqcGc@._V1_Ratio1.0036_AL_.jpg",
    genre: ["Documentary", "Drama"],
    year: 2025,
    rating: 7.8,
    views: 123000,
    quality: "HD",
    slug: "implosion-the-titanic-sub-disaster-2025-new",
    duration: "1h 45m",
    description:
      "In June 2023, the OceanGate submersible imploded, killing all on board. Uncover the extraordinary story of what led to the disaster and its potential prevention, with exclusive access to the USCG investigation and never-before-seen video.",
    country: "United States",
    language: "English",
    downloadUrl: "https://loadedfiles.org/444fb1b298dd6913",
    isNew: true,
    isTrending: true,
  },
  {
    id: "73",
    title: "Walking with the Tall Whites: Aftermath (2024)",
    poster: "https://9jarocks.net/wp-content/uploads/2025/05/Walking-with-the-Tall-Whites-Aftermath_Poster.jpg",
    backdrop: "https://9jarocks.net/wp-content/uploads/2025/05/Walking-with-the-Tall-Whites-Aftermath_Poster.jpg",
    genre: ["Documentary", "Sci-Fi"],
    year: 2024,
    rating: 6.9,
    views: 34000,
    quality: "HD",
    slug: "walking-with-the-tall-whites-aftermath-2024-new",
    duration: "1h 38m",
    description:
      "Walking with the Tall Whites Aftermath is the second documentary in the series, following Charles Hall as he explores humanity's hidden coexistence with three extraterrestrial species on Earth. Based on 'Millennial Hospitality,' Book series.",
    country: "United States",
    language: "English",
    downloadUrl: "https://loadedfiles.org/1c4ff1eeb12d163c",
  },
  {
    id: "74",
    title: "Grimsburg Season 2",
    poster: "https://9jarocks.net/wp-content/uploads/2025/02/Grimsburg_Poster.jpg",
    backdrop: "https://9jarocks.net/wp-content/uploads/2025/02/Grimsburg_Poster.jpg",
    genre: ["Animation", "Comedy", "Crime"],
    year: 2025,
    rating: 7.3,
    views: 87000,
    quality: "HD",
    slug: "grimsburg-season-2-new",
    duration: "Episodes 1-3 Added",
    description:
      "Marvin Flute, who might be the greatest detective ever, has one mystery he still can't crack: his family. He will follow every lead he's got to redeem himself with the ex-wife he never stopped loving.",
    country: "United States",
    language: "English",
    downloadUrl: "https://loadedfiles.org/cd2329272216e5eb",
    multipleDownloads: [
      { label: "Episode 1", url: "https://loadedfiles.org/cd2329272216e5eb" },
      { label: "Episode 2", url: "https://loadedfiles.org/2a49f09f2446ef28" },
      { label: "Episode 3", url: "https://loadedfiles.org/ca9f412a3cb7d5fa" },
    ],
    isNew: true,
  },
  {
    id: "75",
    title: "The Demon's Bride (2025)",
    poster:
      "https://netnaija.xyz/wp-content/uploads/2025/06/The-Demons-Bride-2025-Download-NetNaija.xyz_-683x1024.webp",
    backdrop:
      "https://netnaija.xyz/wp-content/uploads/2025/06/The-Demons-Bride-2025-Download-NetNaija.xyz_-683x1024.webp",
    genre: ["Horror", "Thriller", "Drama"],
    year: 2025,
    rating: 7.2,
    views: 34000,
    quality: "HD",
    slug: "the-demons-bride-2025",
    duration: "1h 42m",
    description:
      "The story of a mother's sacrifice and a family's massacre… When her daughter is severely injured, a desperate mother makes a deal with a demon to save her — but the price must be paid in blood.",
    country: "United States",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/9beed03baec7303d/The_Demons_Bride_(2025)_(NetNaija.xyz).mkv",
    isNew: true,
    isTrending: true,
  },
  {
    id: "76",
    title: "The Accountant 2 (2025)",
    poster:
      "https://netnaija.xyz/wp-content/uploads/2025/06/The-Accountant-2-2025-Download-NetNaija.xyz_-683x1024.webp",
    backdrop:
      "https://netnaija.xyz/wp-content/uploads/2025/06/The-Accountant-2-2025-Download-NetNaija.xyz_-683x1024.webp",
    genre: ["Action", "Crime", "Thriller"],
    year: 2025,
    rating: 7.8,
    views: 89000,
    quality: "HD",
    slug: "the-accountant-2-2025",
    duration: "2h 8m",
    description:
      "When an old acquaintance is murdered, Wolff enlists his lethal brother, Brax, and Marybeth Medina to uncover a deadly conspiracy.",
    cast: ["Ben Affleck", "Jon Bernthal", "Cynthia Addai-Robinson"],
    country: "United States",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/3fa28c6bec0cc204/The_Accountant_2_(2025)_(NetNaija.xyz).mkv",
    isNew: true,
    isTrending: true,
  },
  {
    id: "77",
    title: "Ground Zero (2025)",
    poster: "https://netnaija.xyz/wp-content/uploads/2025/06/Ground-Zero-2025-Download-NetNaija.xyz_-683x1024.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2025/06/Ground-Zero-2025-Download-NetNaija.xyz_-683x1024.webp",
    genre: ["Action", "Drama", "War"],
    year: 2025,
    rating: 8.1,
    views: 67000,
    quality: "HD",
    slug: "ground-zero-2025",
    duration: "2h 15m",
    description: "An Indian army officer leads one of India's most successful counter-terrorism missions in history.",
    country: "India",
    language: "Hindi",
    downloadUrl: "https://netnaijafiles.xyz/75882d8751f72ce3/Ground_Zero_(2025)_(NetNaija.xyz).mkv",
    isNew: true,
    isTrending: true,
  },
  {
    id: "78",
    title: "STRAW (2025)",
    poster: "https://netnaija.xyz/wp-content/uploads/2025/06/STRAW-2025-Download-NetNaija.xyz_-683x1024.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2025/06/STRAW-2025-Download-NetNaija.xyz_-683x1024.webp",
    genre: ["Drama", "Thriller"],
    year: 2025,
    rating: 6.9,
    views: 23000,
    quality: "HD",
    slug: "straw-2025",
    duration: "1h 38m",
    description:
      "A single mother becomes entangled in an unforeseen situation, finding herself at the center of suspicion in an uncaring world.",
    country: "United States",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/917d095ac57eba95/STRAW_(2025)_(NetNaija.xyz).mkv",
    videoUrl: "https://strtape.tech/e/4wkmmryPpPHKKZR/",
    isNew: true,
  },
  {
    id: "79",
    title: "Bhool Chuk Maaf (2025)",
    poster: "https://netnaija.xyz/wp-content/uploads/2025/06/Bhool-Chuk-Maaf-2025-Download-NetNaija.xyz_-683x1024.webp",
    backdrop:
      "https://netnaija.xyz/wp-content/uploads/2025/06/Bhool-Chuk-Maaf-2025-Download-NetNaija.xyz_-683x1024.webp",
    genre: ["Comedy", "Romance", "Fantasy"],
    year: 2025,
    rating: 7.3,
    views: 45000,
    quality: "HD",
    slug: "bhool-chuk-maaf-2025",
    duration: "2h 12m",
    description:
      "A boy from Banaras forgets to vow to Lord Shiva and ends up in a hilarious time loop trying to get married.",
    country: "India",
    language: "Hindi",
    downloadUrl: "https://netnaija.xyz/bhool-chuk-maaf-2025/",
    isNew: true,
  },
  {
    id: "80",
    title: "K.O. (2025)",
    poster: "https://netnaija.xyz/wp-content/uploads/2025/06/K.O.-2025-Download-NetNaija.xyz_-683x1024.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2025/06/K.O.-2025-Download-NetNaija.xyz_-683x1024.webp",
    genre: ["Action", "Crime", "Thriller"],
    year: 2025,
    rating: 7.5,
    views: 56000,
    quality: "HD",
    slug: "ko-2025",
    duration: "1h 47m",
    description: "A former fighter takes on a crime gang in Marseille while searching for a missing boy.",
    country: "France",
    language: "French",
    downloadUrl: "https://netnaijafiles.xyz/f9a894256f16fe17/K.O._(2025)_(NetNaija.xyz).mkv",
    isNew: true,
    isTrending: true,
  },
  {
    id: "81",
    title: "Jaat (2025)",
    poster: "https://netnaija.xyz/wp-content/uploads/2025/06/Jaat-2025-Download-NetNaija.xyz_-683x1024.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2025/06/Jaat-2025-Download-NetNaija.xyz_-683x1024.webp",
    genre: ["Action", "Crime", "Drama"],
    year: 2025,
    rating: 7.1,
    views: 38000,
    quality: "HD",
    slug: "jaat-2025",
    duration: "2h 3m",
    description: "A traveler's violent reaction to a minor offense pulls him into a web of crime and corruption.",
    country: "India",
    language: "Hindi",
    downloadUrl: "https://netnaijafiles.xyz/8e6a5d5476576281/Jaat_(2025)_(NetNaija.xyz).mkv",
    isNew: true,
  },
  {
    id: "82",
    title: "Veera Chandrahasa (2025)",
    poster:
      "https://netnaija.xyz/wp-content/uploads/2025/06/Veera-Chandrahasa-2025-Download-NetNaija.xyz_-683x1024.webp",
    backdrop:
      "https://netnaija.xyz/wp-content/uploads/2025/06/Veera-Chandrahasa-2025-Download-NetNaija.xyz_-683x1024.webp",
    genre: ["Action", "Adventure", "Fantasy"],
    year: 2025,
    rating: 7.4,
    views: 42000,
    quality: "HD",
    slug: "veera-chandrahasa-2025",
    duration: "2h 18m",
    description: "Chandrahasa, raised by a noble, overcomes adversity and emerges as a divine protector.",
    country: "India",
    language: "Telugu",
    downloadUrl: "https://netnaijafiles.xyz/8eaea580857769fe/Veera_Chandrahasa_(2025)_(NetNaija.xyz).mkv",
    isNew: true,
  },
  {
    id: "83",
    title: "Boda Love (2024)",
    poster: "https://9jarocks.net/wp-content/uploads/2025/05/Boda-Love_Poster.jpg",
    backdrop: "https://9jarocks.net/wp-content/uploads/2025/05/Boda-Love_Poster.jpg",
    genre: ["Romance", "Drama", "Comedy"],
    year: 2024,
    rating: 6.8,
    views: 29000,
    quality: "HD",
    slug: "boda-love-2024",
    duration: "1h 52m",
    description: "A boda boda driver helps a British woman who falls victim to a romance scam in Kenya.",
    country: "Kenya",
    language: "English",
    downloadUrl: "https://loadedfiles.org/bb2a0bf0021bdebd",
    isNew: true,
  },
  {
    id: "84",
    title: "The Fire and the Moth (2025)",
    poster: "https://9jarocks.net/wp-content/uploads/2025/06/The-Fire-and-the-Moth_Poster.jpg",
    backdrop: "https://9jarocks.net/wp-content/uploads/2025/06/The-Fire-and-the-Moth_Poster.jpg",
    genre: ["Action", "Crime", "Thriller"],
    year: 2025,
    rating: 7.0,
    views: 31000,
    quality: "HD",
    slug: "the-fire-and-the-moth-2025",
    duration: "1h 44m",
    description: "Chaos ensues when a smuggler escapes with a rare artifact in a gritty Nigerian town.",
    country: "Nigeria",
    language: "English",
    downloadUrl: "https://loadedfiles.org/4908153db3af481b",
    isNew: true,
    isTrending: true,
  },
  {
    id: "85",
    title: "The Party Season 1 (2025)",
    poster: "https://9jarocks.net/wp-content/uploads/2025/05/The-Party-Season-1-Complete-577x1024.jpg",
    backdrop: "https://9jarocks.net/wp-content/uploads/2025/05/The-Party-Season-1-Complete-577x1024.jpg",
    genre: ["Drama", "Mystery", "Thriller"],
    year: 2025,
    rating: 7.6,
    views: 78000,
    quality: "HD",
    slug: "the-party-season-1-2025",
    duration: "3 Episodes",
    description: "A lavish party ends in tragedy and sparks a complex investigation.",
    country: "United States",
    language: "English",
    multipleDownloads: [
      { label: "Episode 1", url: "https://loadedfiles.org/fcd567bacbde2511" },
      { label: "Episode 2", url: "https://loadedfiles.org/aa6455a660afc595" },
      { label: "Episode 3", url: "https://loadedfiles.org/7e2372f9c4d16416" },
    ],
    isNew: true,
    isTrending: true,
  },
  {
    id: "86",
    title: "Fatty and Sons Autos Season 1 (2025)",
    poster:
      "https://9jarocks.net/wp-content/uploads/2025/06/MV5BNjVhMTJkYTMtOGNhMy00OWY5LTgzODgtN2VkOGVlMjY4YjIzXkEyXkFqcGc@._V1_.jpg",
    backdrop:
      "https://9jarocks.net/wp-content/uploads/2025/06/MV5BNjVhMTJkYTMtOGNhMy00OWY5LTgzODgtN2VkOGVlMjY4YjIzXkEyXkFqcGc@._V1_.jpg",
    genre: ["Comedy", "Family", "Drama"],
    year: 2025,
    rating: 7.2,
    views: 65000,
    quality: "HD",
    slug: "fatty-and-sons-autos-season-1-2025",
    duration: "13 Episodes",
    description: "A mechanic deals with his chaotic family and garage life in hilarious situations.",
    country: "United States",
    language: "English",
    multipleDownloads: [
      { label: "Episode 1", url: "https://loadedfiles.org/947375488dcb3c48" },
      { label: "Episode 2", url: "https://loadedfiles.org/92254bab2d26bca7" },
      { label: "Episode 3", url: "https://loadedfiles.org/bc2366d7bb1d4097" },
      { label: "Episode 4", url: "https://loadedfiles.org/ab0056f354f82025" },
      { label: "Episode 5", url: "https://loadedfiles.org/aff4dcf21fa03f13" },
      { label: "Episode 6", url: "https://loadedfiles.org/f1966041ecf32a11" },
      { label: "Episode 7", url: "https://loadedfiles.org/1b0eb2178cded5b8" },
      { label: "Episode 8", url: "https://loadedfiles.org/7fd02dee908b2ebc" },
      { label: "Episode 9", url: "https://loadedfiles.org/34ec7368be352e70" },
      { label: "Episode 10", url: "https://loadedfiles.org/d040c65551246721" },
      { label: "Episode 11", url: "https://loadedfiles.org/9b4504001ac8e84d" },
      { label: "Episode 12", url: "https://loadedfiles.org/e95e20c20bbfc9db" },
      { label: "Episode 13", url: "https://loadedfiles.org/83f0a232923b9b60" },
    ],
    isNew: true,
  },
  {
    id: "87",
    title: "The Mommy Club Season 3 (2025)",
    poster: "https://9jarocks.net/wp-content/uploads/2025/05/The-Mommy-Club_Poster.jpg",
    backdrop: "https://9jarocks.net/wp-content/uploads/2025/05/The-Mommy-Club_Poster.jpg",
    genre: ["Reality", "Drama"],
    year: 2025,
    rating: 6.5,
    views: 43000,
    quality: "HD",
    slug: "the-mommy-club-season-3-2025",
    duration: "3 Episodes + Reunion",
    description: "Jozi's elite moms tackle parenting and drama in this glitzy reality show.",
    country: "South Africa",
    language: "English",
    multipleDownloads: [
      { label: "Episode 11", url: "https://loadedfiles.org/7212fc07008b8286" },
      { label: "Episode 12", url: "https://loadedfiles.org/2b2f54528469bd08" },
      { label: "Episode 13", url: "https://loadedfiles.org/98c37187de04bed1" },
    ],
    isNew: true,
  },
  {
    id: "88",
    title: "Umjolo: The Gone Girl (2024)",
    poster: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/OIP.jpg-0qUIu4AC8MlVB9WzclxL0ZF6IsWkuA.jpeg",
    backdrop: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/OIP.jpg-0qUIu4AC8MlVB9WzclxL0ZF6IsWkuA.jpeg",
    genre: ["Romance", "Drama", "Comedy"],
    year: 2024,
    rating: 7.1,
    views: 52000,
    quality: "HD",
    slug: "umjolo-the-gone-girl-2024",
    duration: "1h 32m",
    description:
      "Follows four women whose love lives intersect at a Valentine's Day wedding none of them will soon forget.",
    cast: ["Gugu Gumede", "Tyson Mathonsi", "Ntando Menzi Ncube"],
    director: "Fikile Mogodi",
    country: "South Africa",
    language: "English",
    downloadUrl: "https://pixeldrain.com/u/8aNfEAot",
    isNew: true,
    isTrending: true,
  },
  {
    id: "89",
    title: "The Last of Us Season 1 (2023)",
    poster:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Last%20of%20us%20season%201.jpg-1pzN5LRSlQ7RYvbG9xu9ZK4XnMoN6h.jpeg",
    backdrop:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Last%20of%20us%20season%201.jpg-1pzN5LRSlQ7RYvbG9xu9ZK4XnMoN6h.jpeg",
    genre: ["Drama", "Horror", "Sci-Fi", "Thriller"],
    year: 2023,
    rating: 8.7,
    views: 2340000,
    quality: "4K",
    slug: "the-last-of-us-season-1-2023",
    duration: "2 Episodes Available",
    description:
      "20 years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal heartbreaking journey as they both must traverse the U.S. and depend on each other for survival.",
    cast: ["Pedro Pascal", "Bella Ramsey", "Anna Torv"],
    country: "United States",
    language: "English",
    multipleDownloads: [
      {
        label: "Episode 1 - Server 1",
        url: "https://pixeldrain.com/u/2cGFdYyb",
      },
      {
        label: "Episode 1 - Server 2",
        url: "https://loadedfiles.org/09e7b490974a60fb",
      },
      {
        label: "Episode 2 - Server 1",
        url: "https://pixeldrain.com/u/atet6f81",
      },
      {
        label: "Episode 2 - Server 2",
        url: "https://loadedfiles.org/f1111a015b690453",
      },
    ],
    isNew: true,
    isTrending: true,
    isFeatured: true,
  },
  {
    id: "90",
    title: "The Last of Us Season 2 (2024)",
    poster:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Last%20of%20us%20season%202.jpg-xoIOob3z6RN0QO0eWp6SN0ZvZ97TJd.jpeg",
    backdrop:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Last%20of%20us%20season%202.jpg-xoIOob3z6RN0QO0eWp6SN0ZvZ97TJd.jpeg",
    genre: ["Drama", "Horror", "Sci-Fi", "Thriller"],
    year: 2024,
    rating: 8.9,
    views: 1890000,
    quality: "4K",
    slug: "the-last-of-us-season-2-2024",
    duration: "2 Episodes Available",
    description:
      "After a global pandemic destroys civilization, a hardened survivor takes charge of a 14-year-old girl who may be humanity's last hope.",
    cast: ["Pedro Pascal", "Bella Ramsey", "Anna Torv"],
    country: "United States",
    language: "English",
    multipleDownloads: [
      {
        label: "Episode 1 - Server 1",
        url: "https://pixeldrain.com/u/C6o3xL9A",
      },
      {
        label: "Episode 2 - Server 1",
        url: "https://pixeldrain.com/u/tFNLAcBK",
      },
      {
        label: "Episode 1 - Server 2",
        url: "https://loadedfiles.org/e5f22fae247f4ff5",
      },
      {
        label: "Episode 2 - Server 2",
        url: "https://loadedfiles.org/09e7b490974a60fb",
      },
    ],
    isNew: true,
    isTrending: true,
    isFeatured: true,
  },
  {
    id: "91",
    title: "Meet the Khumalos (2025)",
    poster:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1171237-768x960.jpg-6wN2OjfT4LqlndBGzRkzzPLGGPeWWd.jpeg",
    backdrop:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1171237-768x960.jpg-6wN2OjfT4LqlndBGzRkzzPLGGPeWWd.jpeg",
    genre: ["Comedy", "Romance", "Drama"],
    year: 2025,
    rating: 7.4,
    views: 45000,
    quality: "HD",
    slug: "meet-the-khumalos-2025",
    duration: "1h 47m",
    description:
      "Hell hath no fury like a woman scorned! Meet Grace Khumalo – her perfect world is thrown off balance when her high school arch rival, Bongi Sithole moves into her elite Umhlanga suburb, right next door! The two arch-enemies are forced to work together as they discover their children have fallen in love! They must move quickly to break them up!",
    cast: ["Grace Khumalo", "Bongi Sithole"],
    country: "South Africa",
    language: "English",
    downloadUrl: "https://loadedfiles.org/7bd5527e5859dc32",
    multipleDownloads: [
      { label: "Server 1 - LoadedFiles", url: "https://loadedfiles.org/7bd5527e5859dc32" },
      { label: "Server 2 - PixelDrain (Faster)", url: "https://pixeldrain.com/u/dhskKRGp" },
    ],
    isNew: true,
    isTrending: true,
  },
  {
    id: "92",
    title: "Predator: Killer of Killers (2025)",
    poster: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-1WLyVj26ZXak2Zkj8BOGxPk4IfdcKi.png",
    backdrop: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-1WLyVj26ZXak2Zkj8BOGxPk4IfdcKi.png",
    genre: ["Action", "Sci-Fi", "Thriller", "Horror"],
    year: 2025,
    rating: 8.2,
    views: 89000,
    quality: "HD",
    slug: "predator-killer-of-killers-2025",
    duration: "2h 8m",
    description:
      "This anthology story follows three of the fiercest warriors in human history: a Viking raider guiding her young son on a bloody quest for revenge; a ninja in feudal Japan who turns against his Samurai brother in a brutal battle for succession; and a WWII pilot who takes to the sky to investigate an otherworldly threat to the Allied cause. But while all these warriors are killers in their own right, they are merely prey for their new opponent — the ultimate killer of killers.",
    cast: ["TBA"],
    director: "Dan Trachtenberg",
    country: "United States",
    language: "English",
    downloadUrl: "https://netnaijafiles.xyz/2ab53eb35ae1bd95/Predator__Killer_of_Killers_(2025)_(NetNaija.xyz).mkv",
    multipleDownloads: [
      {
        label: "Server 1 - NetNaija",
        url: "https://netnaijafiles.xyz/2ab53eb35ae1bd95/Predator__Killer_of_Killers_(2025)_(NetNaija.xyz).mkv",
      },
      { label: "Server 2 - PixelDrain (Faster)", url: "https://pixeldrain.com/u/B7783kif" },
    ],
    isNew: true,
    isTrending: true,
    isFeatured: true,
  },
    {
  id: "93",
  title: "Final Destination Bloodlines (2025)",
  poster: "https://your-hosted-link.com/uploads/r4r.png", // Replace with actual upload URL
  backdrop: "https://your-hosted-link.com/uploads/r4r.png",
  genre: ["Horror", "Thriller"],
  year: 2025,
  rating: 7.4,
  views: 98000,
  quality: "HD",
  slug: "final-destination-bloodlines-2025",
  duration: "1h 42m",
  description:
    "Plagued by a violent recurring nightmare, college student Stefanie heads home to track down the one person who might be able to break the cycle and save her family from the grisly demise that inevitably awaits them all.",
  cast: ["TBA"],
  country: "United States",
  language: "English",
  videoUrl: "https://strtape.tech/e/V80zMyORzYCKwZ0/",
  downloadUrl: "https://strtape.tech/v/V80zMyORzYCKwZ0/Final_Destination_Bloodlines_%282025%29_%5BHC-HDRip%5D_%28NetNaija.xyz%29.mkv.mp4",
  isNew: true,
  isTrending: true,
  isFeatured: true,
},
{
  id: "94",
  title: "Diablo (2025)",
  poster: "https://netnaija.xyz/wp-content/uploads/2025/06/Diablo-2025-Download-NetNaija.xyz_-683x1024.webp",
  backdrop: "https://netnaija.xyz/wp-content/uploads/2025/06/Diablo-2025-Download-NetNaija.xyz_-683x1024.webp",
  genre: ["Action", "Thriller", "Crime"],
  year: 2025,
  rating: 7.8,
  views: 87000,
  quality: "HD",
  slug: "diablo-2025",
  duration: "1h 48m",
  description:
    "Ex-con Kris Chaney seizes the daughter of a Colombian gangster to fulfill a noble promise to the young girl’s mother. When her father enlists both the criminal underworld and a psychotic killer to exact his revenge, Kris relies on everything he’s ever learned to stay alive and keep his word.",
  cast: ["TBA"],
  country: "United States",
  language: "English",
  videoUrl: "https://strtape.tech/e/pYOzeMoJ9efWK2/",
  downloadUrl: "https://strtape.tech/v/pYOzeMoJ9efWK2/Diablo_%282025%29_%28NetNaija.xyz%29.mkv.mp4",
  isNew: true,
  isTrending: false,
  isFeatured: false,
},
{
  id: "95",
  title: "Eleven (2025)",
  poster: "https://netnaija.xyz/wp-content/uploads/2025/06/Eleven-2025-Download-NetNaija.xyz_-683x1024.webp",
  backdrop: "https://netnaija.xyz/wp-content/uploads/2025/06/Eleven-2025-Download-NetNaija.xyz_-683x1024.webp",
  genre: ["Mystery", "Crime", "Thriller"],
  year: 2025,
  rating: 7.2,
  views: 66000,
  quality: "HD",
  slug: "eleven-2025",
  duration: "1h 39m",
  description:
    "A series of murders targeting twins leads a detective down a dark path of revenge and childhood trauma.",
  cast: ["TBA"],
  country: "United States",
  language: "English",
  videoUrl: "https://strtape.tech/e/PjeL0LBPlBhAlv/",
  downloadUrl: "https://strtape.tech/v/PjeL0LBPlBhAlv/Eleven_%282025%29_%28NetNaija.xyz%29.mkv.mp4",
  isNew: true,
  isTrending: false,
  isFeatured: false,
},
{
    id: "93",
    title: "Kings of Joburg Season 2 (2025)",
    poster: "https://netnaija.xyz/wp-content/uploads/2025/01/Kings-of-Joburg-Season-2-Download-NetNaija.xyz_.webp",
    backdrop: "https://netnaija.xyz/wp-content/uploads/2025/01/Kings-of-Joburg-Season-2-Download-NetNaija.xyz_.webp",
    genre: ["Crime", "Drama", "Thriller"],
    year: 2025,
    rating: 8.1,
    views: 145000,
    quality: "HD",
    slug: "kings-of-joburg-season-2-2025",
    duration: "3 Episodes Available",
    description:
      "The Masire brothers rule Johannesburg's criminal underworld, but a supernatural family curse and a tangled web of betrayal threaten to destroy everything they've built. Season 2 continues the gripping saga of power, family, and survival in South Africa's most dangerous city.",
    cast: ["Shona Ferguson", "Connie Ferguson", "Zolisa Xaluva"],
    country: "South Africa",
    language: "English",
    multipleDownloads: [
      {
        label: "Episode 1 - Watch Online",
        url: "https://strtape.tech/e/J31jqXzd3zHj8da",
      },
      {
        label: "Episode 2 - Watch Online",
        url: "https://strtape.tech/e/J31jqXzd3zHj8da",
      },
      {
        label: "Episode 3 - Watch Online",
        url: "https://strtape.tech/e/J31jqXzd3zHj8da",
      },
    ],
    videoUrl: "https://strtape.tech/e/J31jqXzd3zHj8da",
    isNew: true,
    isTrending: true,
    isFeatured: true,
  },
]

// Get recently added movies (same as new movies for now, but could be based on date added)
export const getRecentlyAddedMovies = () => movies.filter((movie) => movie.isNew || movie.year >= 2024).slice(0, 20)

export const getFeaturedMovies = () => movies.filter((movie) => movie.isFeatured)
export const getTrendingMovies = () => movies.filter((movie) => movie.isTrending)
export const getNewMovies = () => movies.filter((movie) => movie.isNew)
export const getMoviesByGenre = (genre: string) => movies.filter((movie) => movie.genre.includes(genre))

// Add this function to handle movie slug lookup
export const getMovieBySlug = (slug: string): Movie | null => {
  return movies.find((movie) => movie.slug === slug) || null
}

// Add this function to get related movies
export const getRelatedMovies = (movieId: string, genres: string[]): Movie[] => {
  return movies.filter((movie) => movie.id !== movieId && movie.genre.some((g) => genres.includes(g))).slice(0, 6)
}

export const getAllMovies = () => movies
export const searchMovies = (query: string) =>
  movies.filter(
    (movie) =>
      movie.title.toLowerCase().includes(query.toLowerCase()) ||
      movie.genre.some((g) => g.toLowerCase().includes(query.toLowerCase())) ||
      movie.cast?.some((c) => c.toLowerCase().includes(query.toLowerCase())),
  )

// Get movies by year
export const getMoviesByYear = (year: number) => movies.filter((movie) => movie.year === year)

// Get movies by country
export const getMoviesByCountry = (country: string) => movies.filter((movie) => movie.country === country)

// Get movies by quality
export const getMoviesByQuality = (quality: string) => movies.filter((movie) => movie.quality === quality)

// Get top rated movies
export const getTopRatedMovies = () => movies.filter((movie) => movie.rating >= 8.0).sort((a, b) => b.rating - a.rating)

// Get most viewed movies
export const getMostViewedMovies = () => movies.sort((a, b) => b.views - a.views).slice(0, 20)

// Get Bollywood movies (Indian movies)
export const getBollywoodMovies = () => movies.filter((movie) => movie.country === "India")

// Get Hollywood movies (US movies)
export const getHollywoodMovies = () => movies.filter((movie) => movie.country === "United States")

// Get Korean movies
export const getKoreanMovies = () => movies.filter((movie) => movie.country === "South Korea")

// Get Chinese movies
export const getChineseMovies = () => movies.filter((movie) => movie.country === "China")

// Get Japanese movies
export const getJapaneseMovies = () => movies.filter((movie) => movie.country === "Japan")

// Get Nigerian movies (Nollywood)
export const getNollywoodMovies = () => movies.filter((movie) => movie.country === "Nigeria")

// Get movies by decade
export const getMoviesByDecade = (decade: number) => {
  const startYear = decade
  const endYear = decade + 9
  return movies.filter((movie) => movie.year >= startYear && movie.year <= endYear)
}

// Get recent movies (last 2 years)
export const getRecentMovies = () => {
  const currentYear = new Date().getFullYear()
  return movies.filter((movie) => movie.year >= currentYear - 1)
}

// Get classic movies (older than 5 years)
export const getClassicMovies = () => {
  const currentYear = new Date().getFullYear()
  return movies.filter((movie) => movie.year <= currentYear - 5)
}

// Get movies with high ratings (7.5+)
export const getHighRatedMovies = () => movies.filter((movie) => movie.rating >= 7.5)

// Get action movies
export const getActionMovies = () => movies.filter((movie) => movie.genre.includes("Action"))

// Get comedy movies
export const getComedyMovies = () => movies.filter((movie) => movie.genre.includes("Comedy"))

// Get drama movies
export const getDramaMovies = () => movies.filter((movie) => movie.genre.includes("Drama"))

// Get horror movies
export const getHorrorMovies = () => movies.filter((movie) => movie.genre.includes("Horror"))

// Get thriller movies
export const getThrillerMovies = () => movies.filter((movie) => movie.genre.includes("Thriller"))

// Get sci-fi movies
export const getSciFiMovies = () => movies.filter((movie) => movie.genre.includes("Sci-Fi"))

// Get animation movies
export const getAnimationMovies = () => movies.filter((movie) => movie.genre.includes("Animation"))

// Get family movies
export const getFamilyMovies = () => movies.filter((movie) => movie.genre.includes("Family"))

// Get romance movies
export const getRomanceMovies = () => movies.filter((movie) => movie.genre.includes("Romance"))

// Get crime movies
export const getCrimeMovies = () => movies.filter((movie) => movie.genre.includes("Crime"))

// Get 4K quality movies
export const get4KMovies = () => movies.filter((movie) => movie.quality === "4K")

// Get HD quality movies
export const getHDMovies = () => movies.filter((movie) => movie.quality === "HD")

// Get random movies
export const getRandomMovies = (count = 10) => {
  const shuffled = [...movies].sort(() => 0.5 - Math.random())
  return shuffled.slice(0, count)
}

// Get similar movies (by genre)
export const getSimilarMovies = (movie: Movie, count = 6) => {
  return movies.filter((m) => m.id !== movie.id && m.genre.some((genre) => movie.genre.includes(genre))).slice(0, count)
}

// Get movies by rating range
export const getMoviesByRatingRange = (minRating: number, maxRating: number) => {
  return movies.filter((movie) => movie.rating >= minRating && movie.rating <= maxRating)
}

// Get movies by view count range
export const getMoviesByViewRange = (minViews: number, maxViews: number) => {
  return movies.filter((movie) => movie.views >= minViews && movie.views <= maxViews)
}
